"""creating other tables

Revision ID: 3c70bc2b32ce
Revises: 4adafffea5d3
Create Date: 2024-07-17 19:11:25.028989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c70bc2b32ce'
down_revision: Union[str, None] = '4adafffea5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniu', table_name='posts')
    op.drop_table('posts')
    op.drop_index('idx_user', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user', 'users', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('email', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fku', ondelete='CASCADE'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('uniu', 'posts', ['email'], unique=True)
    # ### end Alembic commands ###
